### ISSUE TITLE
 "lastDisplayedDate"  If I put this sentence in, I get an error 

### ISSUE THREAD

**Issue by OPEN1004MIND** [zoreet/habit-tracker#11]
After upgrading to v1.1.2 
"lastDisplayedDate": "2023-12-28" - If I put this sentence in, I get an error 
Codeblocks without this sentence will work fine.

Under console error message

Uncaught (in promise) SyntaxError: Expected ',' or '}' after property value in JSON at position 22
    at JSON.parse (<anonymous>)
    at new HabitTracker (plugin:habit-tracker-21:56:31)
    at eval (plugin:habit-tracker-21:247:9)
    at t.initDOM (app.js:1:1539674)
    at t.toDOM (app.js:1:1141789)
    at t.sync (app.js:1:351034)
    at e.sync (app.js:1:332767)
    at app.js:1:373556
    at e.ignore (app.js:1:452767)
    at t.updateInner (app.js:1:373338)
    at t.update (app.js:1:373093)
    at e.update (app.js:1:461415)
    at e.dispatchTransactions (app.js:1:458098)
    at e.dispatch (app.js:1:459981)
    at r (app.js:1:1558455)
    at run (app.js:1:1558678)

**Comment by zoreet** [comment]
From your message above it looks like you forgot to the closing `}`. I assume your code looks something like this

```diff
{
	"path": "path/to/habits",
	"lastDisplayedDate": "2023-12-31"
+ }
```

If adding a `}` at the end doesn't solve it, please paste your whole `habittracker` code and I'll know for sure what the solution is

**Comment by OPEN1004MIND** [comment]
> "lastDisplayedDate": "2023-12-28"

This is my whole code black

```habittracker
{
 "path": "Habits/"
 "lastDisplayedDate": "2023-12-28"
}
```
 "lastDisplayedDate": "2023-12-28"
The screen comes out fine, but when I add this sentence, nothing comes out.

**Comment by zoreet** [comment]
You are missing a trailing comma at the end of the `"path": "Habits/"` line

```diff
{
-	"path": "Habits/"
+	"path": "Habits/",
	"lastDisplayedDate": "2023-12-28"
}
```

**Comment by OPEN1004MIND** [comment]
> ```diff
> +	"path": "Habits/",
> 	"lastDisplayedDate": "2023-12-28"
> ```
WOW !!!
It should now work fine.
Thank you very much
